// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("NCheck")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2014 Paul Hatcher")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
[assembly: AssemblyInformationalVersionAttribute("3.0.0 1ae996")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "NCheck";
        internal const System.String AssemblyCopyright = "Copyright � 2014 Paul Hatcher";
        internal const System.String AssemblyVersion = "3.0.0";
        internal const System.String AssemblyFileVersion = "3.0.0";
        internal const System.String AssemblyInformationalVersion = "3.0.0 1ae996";
    }
}
