// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("2.3.1")]
[assembly: AssemblyFileVersionAttribute("2.3.1")]
[assembly: AssemblyInformationalVersionAttribute("2.3.1 9ae356")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "2.3.1";
        internal const System.String AssemblyFileVersion = "2.3.1";
        internal const System.String AssemblyInformationalVersion = "2.3.1 9ae356";
    }
}
